export {
  formatTraitRecoveryLabel,
  formatLimitedUsesExpandedHint,
} from './format-recovery';
export {
  traitToDetailOption,
  featToDetailOption,
  propertyChipsFromRefs,
  factChip,
  usesFactChips,
  type DetailOptionTraitLike,
  type DetailOptionItemModel,
} from './builders';
export {
  formatAbilityRequirementFact,
  formatHandednessFact,
  formatDamageFact,
  formatWeaponAbilityFact,
  formatWeaponAbilityFactFromProperties,
  formatRangeFact,
  formatSpacesFact,
  formatActionTypeValue,
  formatActionTypeFact,
  formatEnergyFact,
  formatCurrencyFact,
  formatTrainingPointsFact,
  formatAgilityReductionFact,
  formatDamageReductionFact,
  capitalizeSpacesTerm,
  compactFactChip,
  abilityRequirementChip,
  handednessChip,
  damageFactChip,
  weaponAbilityChip,
  rangeFactChip,
  spacesFactChip,
  actionTypeFactChip,
  energyFactChip,
  currencyFactChip,
  trainingPointsFactChip,
  agilityReductionFactChip,
  damageReductionFactChip,
  propertyDescriptorChip,
  namedPropertyDescriptorChips,
  TRAINING_POINTS_COST_LABEL,
  isMechanicPropertyName,
  MECHANIC_PROPERTY_NAMES,
  type AbilityRequirementFact,
  type HandednessLabel,
} from './compact-facts';
export {
  equipmentRefToDetailOption,
} from './equipment-builder';
export {
  buildCombatLookup,
  powerToDetailOption,
  techniqueToDetailOption,
  resolveCombatDetailOption,
} from './combat-builder';
