/**
 * Generated by `npm run db:types` from the live Supabase project.
 * Do not edit by hand. Diff this file after regeneration to detect schema drift.
 * See ADR-0020 / TASK-795.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.1"
  }
  public: {
    Tables: {
      admin_role_audit: {
        Row: {
          actor_id: string
          created_at: string
          id: string
          new_role: string
          old_role: string | null
          target_id: string
        }
        Insert: {
          actor_id: string
          created_at?: string
          id?: string
          new_role: string
          old_role?: string | null
          target_id: string
        }
        Update: {
          actor_id?: string
          created_at?: string
          id?: string
          new_role?: string
          old_role?: string | null
          target_id?: string
        }
        Relationships: []
      }
      campaign_members: {
        Row: {
          campaign_id: string
          user_id: string
        }
        Insert: {
          campaign_id: string
          user_id: string
        }
        Update: {
          campaign_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "campaign_members_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "campaigns"
            referencedColumns: ["id"]
          },
        ]
      }
      campaign_rolls: {
        Row: {
          campaign_id: string
          character_id: string | null
          created_at: string | null
          data: Json
          id: string
          title: string | null
          type: string | null
          user_id: string | null
        }
        Insert: {
          campaign_id: string
          character_id?: string | null
          created_at?: string | null
          data: Json
          id?: string
          title?: string | null
          type?: string | null
          user_id?: string | null
        }
        Update: {
          campaign_id?: string
          character_id?: string | null
          created_at?: string | null
          data?: Json
          id?: string
          title?: string | null
          type?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "campaign_rolls_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "campaigns"
            referencedColumns: ["id"]
          },
        ]
      }
      campaigns: {
        Row: {
          characters: Json
          created_at: string | null
          description: string | null
          id: string
          invite_code: string
          name: string
          owner_id: string
          owner_username: string | null
          updated_at: string | null
        }
        Insert: {
          characters: Json
          created_at?: string | null
          description?: string | null
          id?: string
          invite_code: string
          name: string
          owner_id: string
          owner_username?: string | null
          updated_at?: string | null
        }
        Update: {
          characters?: Json
          created_at?: string | null
          description?: string | null
          id?: string
          invite_code?: string
          name?: string
          owner_id?: string
          owner_username?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      characters: {
        Row: {
          ancestry_name: string | null
          archetype_name: string | null
          client_request_id: string | null
          created_at: string | null
          data: Json
          id: string
          level: number | null
          name: string | null
          status: string | null
          updated_at: string | null
          user_id: string
          visibility: string
        }
        Insert: {
          ancestry_name?: string | null
          archetype_name?: string | null
          client_request_id?: string | null
          created_at?: string | null
          data: Json
          id: string
          level?: number | null
          name?: string | null
          status?: string | null
          updated_at?: string | null
          user_id: string
          visibility?: string
        }
        Update: {
          ancestry_name?: string | null
          archetype_name?: string | null
          client_request_id?: string | null
          created_at?: string | null
          data?: Json
          id?: string
          level?: number | null
          name?: string | null
          status?: string | null
          updated_at?: string | null
          user_id?: string
          visibility?: string
        }
        Relationships: [
          {
            foreignKeyName: "characters_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "user_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      codex_archetype_levels: {
        Row: {
          archetype_id: string
          armaments: string | null
          created_at: string
          equipment: string | null
          feats: string | null
          id: number
          level: number
          notes: string | null
          powers: string | null
          remove_armaments: string | null
          remove_feats: string | null
          remove_powers: string | null
          remove_techniques: string | null
          skills: string | null
          techniques: string | null
          updated_at: string
        }
        Insert: {
          archetype_id: string
          armaments?: string | null
          created_at?: string
          equipment?: string | null
          feats?: string | null
          id?: number
          level: number
          notes?: string | null
          powers?: string | null
          remove_armaments?: string | null
          remove_feats?: string | null
          remove_powers?: string | null
          remove_techniques?: string | null
          skills?: string | null
          techniques?: string | null
          updated_at?: string
        }
        Update: {
          archetype_id?: string
          armaments?: string | null
          created_at?: string
          equipment?: string | null
          feats?: string | null
          id?: number
          level?: number
          notes?: string | null
          powers?: string | null
          remove_armaments?: string | null
          remove_feats?: string | null
          remove_powers?: string | null
          remove_techniques?: string | null
          skills?: string | null
          techniques?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "codex_archetype_levels_archetype_id_fkey"
            columns: ["archetype_id"]
            isOneToOne: false
            referencedRelation: "codex_archetypes"
            referencedColumns: ["id"]
          },
        ]
      }
      codex_archetypes: {
        Row: {
          archetype_ability: string | null
          description: string | null
          id: string
          level1_armaments: string | null
          level1_equipment: string | null
          level1_feats: string | null
          level1_guidance_groups: Json | null
          level1_innate_powers: string | null
          level1_loadouts: Json | null
          level1_notes: string | null
          level1_powers: string | null
          level1_recommend_unarmed_prowess: boolean
          level1_recommended_abilities: Json | null
          level1_remove_armaments: string | null
          level1_remove_feats: string | null
          level1_remove_powers: string | null
          level1_remove_techniques: string | null
          level1_skills: string | null
          level1_techniques: string | null
          martial_prof_level5: number | null
          martial_prof_start: number | null
          name: string | null
          path_data: Json | null
          power_prof_level5: number | null
          power_prof_start: number | null
          secondary_ability: string | null
          type: string | null
          updated_at: string
        }
        Insert: {
          archetype_ability?: string | null
          description?: string | null
          id: string
          level1_armaments?: string | null
          level1_equipment?: string | null
          level1_feats?: string | null
          level1_guidance_groups?: Json | null
          level1_innate_powers?: string | null
          level1_loadouts?: Json | null
          level1_notes?: string | null
          level1_powers?: string | null
          level1_recommend_unarmed_prowess?: boolean
          level1_recommended_abilities?: Json | null
          level1_remove_armaments?: string | null
          level1_remove_feats?: string | null
          level1_remove_powers?: string | null
          level1_remove_techniques?: string | null
          level1_skills?: string | null
          level1_techniques?: string | null
          martial_prof_level5?: number | null
          martial_prof_start?: number | null
          name?: string | null
          path_data?: Json | null
          power_prof_level5?: number | null
          power_prof_start?: number | null
          secondary_ability?: string | null
          type?: string | null
          updated_at?: string
        }
        Update: {
          archetype_ability?: string | null
          description?: string | null
          id?: string
          level1_armaments?: string | null
          level1_equipment?: string | null
          level1_feats?: string | null
          level1_guidance_groups?: Json | null
          level1_innate_powers?: string | null
          level1_loadouts?: Json | null
          level1_notes?: string | null
          level1_powers?: string | null
          level1_recommend_unarmed_prowess?: boolean
          level1_recommended_abilities?: Json | null
          level1_remove_armaments?: string | null
          level1_remove_feats?: string | null
          level1_remove_powers?: string | null
          level1_remove_techniques?: string | null
          level1_skills?: string | null
          level1_techniques?: string | null
          martial_prof_level5?: number | null
          martial_prof_start?: number | null
          name?: string | null
          path_data?: Json | null
          power_prof_level5?: number | null
          power_prof_start?: number | null
          secondary_ability?: string | null
          type?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      codex_change_logs: {
        Row: {
          after_data: Json | null
          before_data: Json | null
          changed_at: string
          changed_by_user_id: string
          changed_fields: Json | null
          entity_id: string
          entity_type: string
          id: string
          operation: string
        }
        Insert: {
          after_data?: Json | null
          before_data?: Json | null
          changed_at?: string
          changed_by_user_id: string
          changed_fields?: Json | null
          entity_id: string
          entity_type: string
          id?: string
          operation: string
        }
        Update: {
          after_data?: Json | null
          before_data?: Json | null
          changed_at?: string
          changed_by_user_id?: string
          changed_fields?: Json | null
          entity_id?: string
          entity_type?: string
          id?: string
          operation?: string
        }
        Relationships: []
      }
      codex_creature_feats: {
        Row: {
          description: string | null
          feat_lvl: number | null
          feat_points: number | null
          id: string
          lvl_req: number | null
          mechanic: boolean | null
          name: string | null
          updated_at: string
        }
        Insert: {
          description?: string | null
          feat_lvl?: number | null
          feat_points?: number | null
          id: string
          lvl_req?: number | null
          mechanic?: boolean | null
          name?: string | null
          updated_at?: string
        }
        Update: {
          description?: string | null
          feat_lvl?: number | null
          feat_points?: number | null
          id?: string
          lvl_req?: number | null
          mechanic?: boolean | null
          name?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      codex_equipment: {
        Row: {
          category: string | null
          currency: number | null
          description: string | null
          id: string
          image_id: string | null
          image_url: string | null
          name: string | null
          rarity: string | null
          updated_at: string
        }
        Insert: {
          category?: string | null
          currency?: number | null
          description?: string | null
          id: string
          image_id?: string | null
          image_url?: string | null
          name?: string | null
          rarity?: string | null
          updated_at?: string
        }
        Update: {
          category?: string | null
          currency?: number | null
          description?: string | null
          id?: string
          image_id?: string | null
          image_url?: string | null
          name?: string | null
          rarity?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "codex_equipment_image_id_fkey"
            columns: ["image_id"]
            isOneToOne: false
            referencedRelation: "realms_images"
            referencedColumns: ["id"]
          },
        ]
      }
      codex_feats: {
        Row: {
          abil_req_val: string | null
          ability: string | null
          ability_req: string | null
          base_feat_id: string | null
          category: string | null
          char_feat: boolean | null
          description: string | null
          feat_cat_req: string | null
          feat_lvl: number | null
          id: string
          lvl_req: number | null
          mart_abil_req: number | null
          mart_prof_req: number | null
          name: string | null
          pow_abil_req: number | null
          pow_prof_req: number | null
          rec_period: string | null
          req_desc: string | null
          skill_req: string | null
          skill_req_val: string | null
          speed_req: number | null
          state_feat: boolean | null
          tags: string | null
          updated_at: string
          uses_per_rec: number | null
        }
        Insert: {
          abil_req_val?: string | null
          ability?: string | null
          ability_req?: string | null
          base_feat_id?: string | null
          category?: string | null
          char_feat?: boolean | null
          description?: string | null
          feat_cat_req?: string | null
          feat_lvl?: number | null
          id: string
          lvl_req?: number | null
          mart_abil_req?: number | null
          mart_prof_req?: number | null
          name?: string | null
          pow_abil_req?: number | null
          pow_prof_req?: number | null
          rec_period?: string | null
          req_desc?: string | null
          skill_req?: string | null
          skill_req_val?: string | null
          speed_req?: number | null
          state_feat?: boolean | null
          tags?: string | null
          updated_at?: string
          uses_per_rec?: number | null
        }
        Update: {
          abil_req_val?: string | null
          ability?: string | null
          ability_req?: string | null
          base_feat_id?: string | null
          category?: string | null
          char_feat?: boolean | null
          description?: string | null
          feat_cat_req?: string | null
          feat_lvl?: number | null
          id?: string
          lvl_req?: number | null
          mart_abil_req?: number | null
          mart_prof_req?: number | null
          name?: string | null
          pow_abil_req?: number | null
          pow_prof_req?: number | null
          rec_period?: string | null
          req_desc?: string | null
          skill_req?: string | null
          skill_req_val?: string | null
          speed_req?: number | null
          state_feat?: boolean | null
          tags?: string | null
          updated_at?: string
          uses_per_rec?: number | null
        }
        Relationships: []
      }
      codex_parts: {
        Row: {
          base_en: number | null
          base_tp: number | null
          category: string | null
          defense: string | null
          description: string | null
          duration: boolean | null
          id: string
          mechanic: boolean | null
          name: string | null
          op_1_desc: string | null
          op_1_en: number | null
          op_1_tp: number | null
          op_2_desc: string | null
          op_2_en: number | null
          op_2_tp: number | null
          op_3_desc: string | null
          op_3_en: number | null
          op_3_tp: number | null
          percentage: boolean | null
          type: string | null
          updated_at: string
        }
        Insert: {
          base_en?: number | null
          base_tp?: number | null
          category?: string | null
          defense?: string | null
          description?: string | null
          duration?: boolean | null
          id: string
          mechanic?: boolean | null
          name?: string | null
          op_1_desc?: string | null
          op_1_en?: number | null
          op_1_tp?: number | null
          op_2_desc?: string | null
          op_2_en?: number | null
          op_2_tp?: number | null
          op_3_desc?: string | null
          op_3_en?: number | null
          op_3_tp?: number | null
          percentage?: boolean | null
          type?: string | null
          updated_at?: string
        }
        Update: {
          base_en?: number | null
          base_tp?: number | null
          category?: string | null
          defense?: string | null
          description?: string | null
          duration?: boolean | null
          id?: string
          mechanic?: boolean | null
          name?: string | null
          op_1_desc?: string | null
          op_1_en?: number | null
          op_1_tp?: number | null
          op_2_desc?: string | null
          op_2_en?: number | null
          op_2_tp?: number | null
          op_3_desc?: string | null
          op_3_en?: number | null
          op_3_tp?: number | null
          percentage?: boolean | null
          type?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      codex_properties: {
        Row: {
          base_c: number | null
          base_ip: number | null
          base_tp: number | null
          description: string | null
          id: string
          mechanic: boolean | null
          name: string | null
          op_1_c: number | null
          op_1_desc: string | null
          op_1_ip: number | null
          op_1_tp: number | null
          type: string | null
          updated_at: string
        }
        Insert: {
          base_c?: number | null
          base_ip?: number | null
          base_tp?: number | null
          description?: string | null
          id: string
          mechanic?: boolean | null
          name?: string | null
          op_1_c?: number | null
          op_1_desc?: string | null
          op_1_ip?: number | null
          op_1_tp?: number | null
          type?: string | null
          updated_at?: string
        }
        Update: {
          base_c?: number | null
          base_ip?: number | null
          base_tp?: number | null
          description?: string | null
          id?: string
          mechanic?: boolean | null
          name?: string | null
          op_1_c?: number | null
          op_1_desc?: string | null
          op_1_ip?: number | null
          op_1_tp?: number | null
          type?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      codex_retired_ids: {
        Row: {
          entity_type: string
          id: string
          retired_at: string
          retired_by: string | null
        }
        Insert: {
          entity_type: string
          id: string
          retired_at?: string
          retired_by?: string | null
        }
        Update: {
          entity_type?: string
          id?: string
          retired_at?: string
          retired_by?: string | null
        }
        Relationships: []
      }
      codex_skills: {
        Row: {
          ability: string | null
          base_skill: string | null
          craft_failure_desc: string | null
          craft_success_desc: string | null
          description: string | null
          ds_calc: string | null
          failure_desc: string | null
          id: string
          name: string | null
          success_desc: string | null
          updated_at: string
        }
        Insert: {
          ability?: string | null
          base_skill?: string | null
          craft_failure_desc?: string | null
          craft_success_desc?: string | null
          description?: string | null
          ds_calc?: string | null
          failure_desc?: string | null
          id: string
          name?: string | null
          success_desc?: string | null
          updated_at?: string
        }
        Update: {
          ability?: string | null
          base_skill?: string | null
          craft_failure_desc?: string | null
          craft_success_desc?: string | null
          description?: string | null
          ds_calc?: string | null
          failure_desc?: string | null
          id?: string
          name?: string | null
          success_desc?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      codex_species: {
        Row: {
          adulthood_lifespan: string | null
          ancestry_traits: string | null
          ave_hgt_cm: number | null
          ave_wgt_kg: number | null
          characteristics: string | null
          description: string | null
          flaws: string | null
          id: string
          image_id: string | null
          image_url: string | null
          is_starter: boolean
          languages: string | null
          name: string | null
          sizes: string | null
          skills: string | null
          species_traits: string | null
          type: string | null
          updated_at: string
        }
        Insert: {
          adulthood_lifespan?: string | null
          ancestry_traits?: string | null
          ave_hgt_cm?: number | null
          ave_wgt_kg?: number | null
          characteristics?: string | null
          description?: string | null
          flaws?: string | null
          id: string
          image_id?: string | null
          image_url?: string | null
          is_starter?: boolean
          languages?: string | null
          name?: string | null
          sizes?: string | null
          skills?: string | null
          species_traits?: string | null
          type?: string | null
          updated_at?: string
        }
        Update: {
          adulthood_lifespan?: string | null
          ancestry_traits?: string | null
          ave_hgt_cm?: number | null
          ave_wgt_kg?: number | null
          characteristics?: string | null
          description?: string | null
          flaws?: string | null
          id?: string
          image_id?: string | null
          image_url?: string | null
          is_starter?: boolean
          languages?: string | null
          name?: string | null
          sizes?: string | null
          skills?: string | null
          species_traits?: string | null
          type?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "codex_species_image_id_fkey"
            columns: ["image_id"]
            isOneToOne: false
            referencedRelation: "realms_images"
            referencedColumns: ["id"]
          },
        ]
      }
      codex_traits: {
        Row: {
          characteristic: boolean | null
          description: string | null
          flaw: boolean | null
          id: string
          name: string | null
          option_trait_ids: string | null
          rec_period: string | null
          updated_at: string
          uses_per_rec: number | null
        }
        Insert: {
          characteristic?: boolean | null
          description?: string | null
          flaw?: boolean | null
          id: string
          name?: string | null
          option_trait_ids?: string | null
          rec_period?: string | null
          updated_at?: string
          uses_per_rec?: number | null
        }
        Update: {
          characteristic?: boolean | null
          description?: string | null
          flaw?: boolean | null
          id?: string
          name?: string | null
          option_trait_ids?: string | null
          rec_period?: string | null
          updated_at?: string
          uses_per_rec?: number | null
        }
        Relationships: []
      }
      core_rules: {
        Row: {
          data: Json
          id: string
          updated_at: string | null
        }
        Insert: {
          data: Json
          id: string
          updated_at?: string | null
        }
        Update: {
          data?: Json
          id?: string
          updated_at?: string | null
        }
        Relationships: []
      }
      crafting_sessions: {
        Row: {
          created_at: string | null
          currency_cost: number | null
          data: Json
          id: string
          item_name: string | null
          status: string
          updated_at: string | null
          user_id: string
        }
        Insert: {
          created_at?: string | null
          currency_cost?: number | null
          data?: Json
          id?: string
          item_name?: string | null
          status?: string
          updated_at?: string | null
          user_id: string
        }
        Update: {
          created_at?: string | null
          currency_cost?: number | null
          data?: Json
          id?: string
          item_name?: string | null
          status?: string
          updated_at?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "crafting_sessions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "user_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      encounters: {
        Row: {
          created_at: string | null
          data: Json
          id: string
          name: string | null
          status: string | null
          type: string | null
          updated_at: string | null
          user_id: string
        }
        Insert: {
          created_at?: string | null
          data: Json
          id: string
          name?: string | null
          status?: string | null
          type?: string | null
          updated_at?: string | null
          user_id: string
        }
        Update: {
          created_at?: string | null
          data?: Json
          id?: string
          name?: string | null
          status?: string | null
          type?: string | null
          updated_at?: string | null
          user_id?: string
        }
        Relationships: []
      }
      official_creatures: {
        Row: {
          created_at: string | null
          description: string | null
          energy_points: number | null
          hit_points: number | null
          id: string
          image_id: string | null
          image_url: string | null
          level: number | null
          name: string | null
          payload: Json | null
          size: string | null
          type: string | null
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          description?: string | null
          energy_points?: number | null
          hit_points?: number | null
          id: string
          image_id?: string | null
          image_url?: string | null
          level?: number | null
          name?: string | null
          payload?: Json | null
          size?: string | null
          type?: string | null
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          description?: string | null
          energy_points?: number | null
          hit_points?: number | null
          id?: string
          image_id?: string | null
          image_url?: string | null
          level?: number | null
          name?: string | null
          payload?: Json | null
          size?: string | null
          type?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "official_creatures_image_id_fkey"
            columns: ["image_id"]
            isOneToOne: false
            referencedRelation: "realms_images"
            referencedColumns: ["id"]
          },
        ]
      }
      official_empowered_techniques: {
        Row: {
          action_type: string | null
          created_at: string | null
          damage: Json
          description: string | null
          duration_type: string | null
          duration_value: number | null
          id: string
          image_id: string | null
          image_url: string | null
          name: string | null
          payload: Json
          range_steps: number | null
          updated_at: string | null
        }
        Insert: {
          action_type?: string | null
          created_at?: string | null
          damage?: Json
          description?: string | null
          duration_type?: string | null
          duration_value?: number | null
          id: string
          image_id?: string | null
          image_url?: string | null
          name?: string | null
          payload?: Json
          range_steps?: number | null
          updated_at?: string | null
        }
        Update: {
          action_type?: string | null
          created_at?: string | null
          damage?: Json
          description?: string | null
          duration_type?: string | null
          duration_value?: number | null
          id?: string
          image_id?: string | null
          image_url?: string | null
          name?: string | null
          payload?: Json
          range_steps?: number | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "official_empowered_techniques_image_id_fkey"
            columns: ["image_id"]
            isOneToOne: false
            referencedRelation: "realms_images"
            referencedColumns: ["id"]
          },
        ]
      }
      official_enhanced_items: {
        Row: {
          base_item_description: string | null
          base_item_id: string | null
          base_item_name: string
          base_item_source: string
          created_at: string
          currency_cost: number
          description: string | null
          id: string
          name: string
          payload: Json
          power_id: string
          power_name: string
          power_source: string
          rarity: string
          updated_at: string
          uses_count: number | null
          uses_type: string
        }
        Insert: {
          base_item_description?: string | null
          base_item_id?: string | null
          base_item_name: string
          base_item_source: string
          created_at?: string
          currency_cost: number
          description?: string | null
          id?: string
          name: string
          payload?: Json
          power_id: string
          power_name: string
          power_source: string
          rarity: string
          updated_at?: string
          uses_count?: number | null
          uses_type: string
        }
        Update: {
          base_item_description?: string | null
          base_item_id?: string | null
          base_item_name?: string
          base_item_source?: string
          created_at?: string
          currency_cost?: number
          description?: string | null
          id?: string
          name?: string
          payload?: Json
          power_id?: string
          power_name?: string
          power_source?: string
          rarity?: string
          updated_at?: string
          uses_count?: number | null
          uses_type?: string
        }
        Relationships: []
      }
      official_items: {
        Row: {
          ability_requirement: Json | null
          agility_reduction: number | null
          armor_value: number | null
          costs: Json | null
          created_at: string | null
          critical_range_increase: number | null
          damage: Json
          damage_reduction: number | null
          description: string | null
          id: string
          image_id: string | null
          image_url: string | null
          is_two_handed: boolean | null
          name: string | null
          payload: Json | null
          properties: Json
          range_steps: number | null
          rarity: string | null
          shield_damage: Json | null
          shield_dr: Json | null
          type: string | null
          updated_at: string | null
        }
        Insert: {
          ability_requirement?: Json | null
          agility_reduction?: number | null
          armor_value?: number | null
          costs?: Json | null
          created_at?: string | null
          critical_range_increase?: number | null
          damage?: Json
          damage_reduction?: number | null
          description?: string | null
          id: string
          image_id?: string | null
          image_url?: string | null
          is_two_handed?: boolean | null
          name?: string | null
          payload?: Json | null
          properties?: Json
          range_steps?: number | null
          rarity?: string | null
          shield_damage?: Json | null
          shield_dr?: Json | null
          type?: string | null
          updated_at?: string | null
        }
        Update: {
          ability_requirement?: Json | null
          agility_reduction?: number | null
          armor_value?: number | null
          costs?: Json | null
          created_at?: string | null
          critical_range_increase?: number | null
          damage?: Json
          damage_reduction?: number | null
          description?: string | null
          id?: string
          image_id?: string | null
          image_url?: string | null
          is_two_handed?: boolean | null
          name?: string | null
          payload?: Json | null
          properties?: Json
          range_steps?: number | null
          rarity?: string | null
          shield_damage?: Json | null
          shield_dr?: Json | null
          type?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "official_items_image_id_fkey"
            columns: ["image_id"]
            isOneToOne: false
            referencedRelation: "realms_images"
            referencedColumns: ["id"]
          },
        ]
      }
      official_powers: {
        Row: {
          action_type: string | null
          area_level: number | null
          area_type: string | null
          created_at: string | null
          damage: Json | null
          description: string | null
          duration_type: string | null
          duration_value: number | null
          id: string
          image_id: string | null
          image_url: string | null
          innate: boolean | null
          is_reaction: boolean | null
          name: string | null
          payload: Json | null
          range_steps: number | null
          updated_at: string | null
        }
        Insert: {
          action_type?: string | null
          area_level?: number | null
          area_type?: string | null
          created_at?: string | null
          damage?: Json | null
          description?: string | null
          duration_type?: string | null
          duration_value?: number | null
          id: string
          image_id?: string | null
          image_url?: string | null
          innate?: boolean | null
          is_reaction?: boolean | null
          name?: string | null
          payload?: Json | null
          range_steps?: number | null
          updated_at?: string | null
        }
        Update: {
          action_type?: string | null
          area_level?: number | null
          area_type?: string | null
          created_at?: string | null
          damage?: Json | null
          description?: string | null
          duration_type?: string | null
          duration_value?: number | null
          id?: string
          image_id?: string | null
          image_url?: string | null
          innate?: boolean | null
          is_reaction?: boolean | null
          name?: string | null
          payload?: Json | null
          range_steps?: number | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "official_powers_image_id_fkey"
            columns: ["image_id"]
            isOneToOne: false
            referencedRelation: "realms_images"
            referencedColumns: ["id"]
          },
        ]
      }
      official_techniques: {
        Row: {
          action_type: string | null
          created_at: string | null
          damage: Json
          description: string | null
          duration_type: string | null
          duration_value: number | null
          id: string
          image_id: string | null
          image_url: string | null
          name: string | null
          payload: Json | null
          range_steps: number | null
          updated_at: string | null
        }
        Insert: {
          action_type?: string | null
          created_at?: string | null
          damage?: Json
          description?: string | null
          duration_type?: string | null
          duration_value?: number | null
          id: string
          image_id?: string | null
          image_url?: string | null
          name?: string | null
          payload?: Json | null
          range_steps?: number | null
          updated_at?: string | null
        }
        Update: {
          action_type?: string | null
          created_at?: string | null
          damage?: Json
          description?: string | null
          duration_type?: string | null
          duration_value?: number | null
          id?: string
          image_id?: string | null
          image_url?: string | null
          name?: string | null
          payload?: Json | null
          range_steps?: number | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "official_techniques_image_id_fkey"
            columns: ["image_id"]
            isOneToOne: false
            referencedRelation: "realms_images"
            referencedColumns: ["id"]
          },
        ]
      }
      realms_image_categories: {
        Row: {
          category: Database["public"]["Enums"]["realms_image_category"]
          image_id: string
        }
        Insert: {
          category: Database["public"]["Enums"]["realms_image_category"]
          image_id: string
        }
        Update: {
          category?: Database["public"]["Enums"]["realms_image_category"]
          image_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "realms_image_categories_image_id_fkey"
            columns: ["image_id"]
            isOneToOne: false
            referencedRelation: "realms_images"
            referencedColumns: ["id"]
          },
        ]
      }
      realms_images: {
        Row: {
          created_at: string
          created_by: string | null
          id: string
          name: string
          public_url: string
          storage_path: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          id?: string
          name: string
          public_url: string
          storage_path: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          id?: string
          name?: string
          public_url?: string
          storage_path?: string
          updated_at?: string
        }
        Relationships: []
      }
      role_policies: {
        Row: {
          max_campaigns: number
          max_characters: number
          max_custom_armaments: number
          max_custom_creatures: number
          max_custom_powers: number
          max_custom_techniques: number
          max_players_per_campaign: number
          permissions: Json
          role: Database["public"]["Enums"]["UserRole"]
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          max_campaigns: number
          max_characters: number
          max_custom_armaments: number
          max_custom_creatures: number
          max_custom_powers: number
          max_custom_techniques: number
          max_players_per_campaign: number
          permissions?: Json
          role: Database["public"]["Enums"]["UserRole"]
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          max_campaigns?: number
          max_characters?: number
          max_custom_armaments?: number
          max_custom_creatures?: number
          max_custom_powers?: number
          max_custom_techniques?: number
          max_players_per_campaign?: number
          permissions?: Json
          role?: Database["public"]["Enums"]["UserRole"]
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      user_creatures: {
        Row: {
          created_at: string | null
          description: string | null
          energy_points: number | null
          hit_points: number | null
          id: string
          image_id: string | null
          image_url: string | null
          level: number | null
          name: string | null
          payload: Json | null
          size: string | null
          type: string | null
          updated_at: string | null
          user_id: string
        }
        Insert: {
          created_at?: string | null
          description?: string | null
          energy_points?: number | null
          hit_points?: number | null
          id: string
          image_id?: string | null
          image_url?: string | null
          level?: number | null
          name?: string | null
          payload?: Json | null
          size?: string | null
          type?: string | null
          updated_at?: string | null
          user_id: string
        }
        Update: {
          created_at?: string | null
          description?: string | null
          energy_points?: number | null
          hit_points?: number | null
          id?: string
          image_id?: string | null
          image_url?: string | null
          level?: number | null
          name?: string | null
          payload?: Json | null
          size?: string | null
          type?: string | null
          updated_at?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_creatures_image_id_fkey"
            columns: ["image_id"]
            isOneToOne: false
            referencedRelation: "realms_images"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_creatures_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "user_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      user_empowered_techniques: {
        Row: {
          action_type: string | null
          created_at: string | null
          damage: Json
          description: string | null
          duration_type: string | null
          duration_value: number | null
          id: string
          image_id: string | null
          image_url: string | null
          name: string | null
          payload: Json
          range_steps: number | null
          updated_at: string | null
          user_id: string
        }
        Insert: {
          action_type?: string | null
          created_at?: string | null
          damage?: Json
          description?: string | null
          duration_type?: string | null
          duration_value?: number | null
          id: string
          image_id?: string | null
          image_url?: string | null
          name?: string | null
          payload?: Json
          range_steps?: number | null
          updated_at?: string | null
          user_id: string
        }
        Update: {
          action_type?: string | null
          created_at?: string | null
          damage?: Json
          description?: string | null
          duration_type?: string | null
          duration_value?: number | null
          id?: string
          image_id?: string | null
          image_url?: string | null
          name?: string | null
          payload?: Json
          range_steps?: number | null
          updated_at?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_empowered_techniques_image_id_fkey"
            columns: ["image_id"]
            isOneToOne: false
            referencedRelation: "realms_images"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_empowered_techniques_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "user_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      user_enhanced_items: {
        Row: {
          created_at: string | null
          data: Json
          id: string
          name: string | null
          updated_at: string | null
          user_id: string
        }
        Insert: {
          created_at?: string | null
          data?: Json
          id?: string
          name?: string | null
          updated_at?: string | null
          user_id: string
        }
        Update: {
          created_at?: string | null
          data?: Json
          id?: string
          name?: string | null
          updated_at?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_enhanced_items_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "user_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      user_items: {
        Row: {
          ability_requirement: Json | null
          agility_reduction: number | null
          armor_value: number | null
          costs: Json | null
          created_at: string | null
          critical_range_increase: number | null
          damage: Json
          damage_reduction: number | null
          description: string | null
          id: string
          image_id: string | null
          image_url: string | null
          is_two_handed: boolean | null
          name: string | null
          payload: Json | null
          properties: Json
          range_steps: number | null
          rarity: string | null
          shield_damage: Json | null
          shield_dr: Json | null
          type: string | null
          updated_at: string | null
          user_id: string
        }
        Insert: {
          ability_requirement?: Json | null
          agility_reduction?: number | null
          armor_value?: number | null
          costs?: Json | null
          created_at?: string | null
          critical_range_increase?: number | null
          damage?: Json
          damage_reduction?: number | null
          description?: string | null
          id: string
          image_id?: string | null
          image_url?: string | null
          is_two_handed?: boolean | null
          name?: string | null
          payload?: Json | null
          properties?: Json
          range_steps?: number | null
          rarity?: string | null
          shield_damage?: Json | null
          shield_dr?: Json | null
          type?: string | null
          updated_at?: string | null
          user_id: string
        }
        Update: {
          ability_requirement?: Json | null
          agility_reduction?: number | null
          armor_value?: number | null
          costs?: Json | null
          created_at?: string | null
          critical_range_increase?: number | null
          damage?: Json
          damage_reduction?: number | null
          description?: string | null
          id?: string
          image_id?: string | null
          image_url?: string | null
          is_two_handed?: boolean | null
          name?: string | null
          payload?: Json | null
          properties?: Json
          range_steps?: number | null
          rarity?: string | null
          shield_damage?: Json | null
          shield_dr?: Json | null
          type?: string | null
          updated_at?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_items_image_id_fkey"
            columns: ["image_id"]
            isOneToOne: false
            referencedRelation: "realms_images"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_items_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "user_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      user_powers: {
        Row: {
          action_type: string | null
          area_level: number | null
          area_type: string | null
          created_at: string | null
          damage: Json
          description: string | null
          duration_type: string | null
          duration_value: number | null
          id: string
          image_id: string | null
          image_url: string | null
          innate: boolean | null
          is_reaction: boolean | null
          name: string | null
          payload: Json | null
          range_steps: number | null
          updated_at: string | null
          user_id: string
        }
        Insert: {
          action_type?: string | null
          area_level?: number | null
          area_type?: string | null
          created_at?: string | null
          damage?: Json
          description?: string | null
          duration_type?: string | null
          duration_value?: number | null
          id: string
          image_id?: string | null
          image_url?: string | null
          innate?: boolean | null
          is_reaction?: boolean | null
          name?: string | null
          payload?: Json | null
          range_steps?: number | null
          updated_at?: string | null
          user_id: string
        }
        Update: {
          action_type?: string | null
          area_level?: number | null
          area_type?: string | null
          created_at?: string | null
          damage?: Json
          description?: string | null
          duration_type?: string | null
          duration_value?: number | null
          id?: string
          image_id?: string | null
          image_url?: string | null
          innate?: boolean | null
          is_reaction?: boolean | null
          name?: string | null
          payload?: Json | null
          range_steps?: number | null
          updated_at?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_powers_image_id_fkey"
            columns: ["image_id"]
            isOneToOne: false
            referencedRelation: "realms_images"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_powers_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "user_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      user_profiles: {
        Row: {
          created_at: string
          display_name: string | null
          email: string | null
          id: string
          last_username_change: string | null
          photo_url: string | null
          role: Database["public"]["Enums"]["UserRole"]
          updated_at: string
          username: string | null
          username_display: string | null
        }
        Insert: {
          created_at?: string
          display_name?: string | null
          email?: string | null
          id: string
          last_username_change?: string | null
          photo_url?: string | null
          role?: Database["public"]["Enums"]["UserRole"]
          updated_at?: string
          username?: string | null
          username_display?: string | null
        }
        Update: {
          created_at?: string
          display_name?: string | null
          email?: string | null
          id?: string
          last_username_change?: string | null
          photo_url?: string | null
          role?: Database["public"]["Enums"]["UserRole"]
          updated_at?: string
          username?: string | null
          username_display?: string | null
        }
        Relationships: []
      }
      user_species: {
        Row: {
          adulthood_lifespan: string | null
          ancestry_traits: string | null
          ave_hgt_cm: number | null
          ave_wgt_kg: number | null
          characteristics: string | null
          created_at: string | null
          description: string | null
          flaws: string | null
          id: string
          image_id: string | null
          image_url: string | null
          languages: string | null
          name: string | null
          payload: Json | null
          sizes: string | null
          skills: string | null
          species_traits: string | null
          type: string | null
          updated_at: string | null
          user_id: string
        }
        Insert: {
          adulthood_lifespan?: string | null
          ancestry_traits?: string | null
          ave_hgt_cm?: number | null
          ave_wgt_kg?: number | null
          characteristics?: string | null
          created_at?: string | null
          description?: string | null
          flaws?: string | null
          id: string
          image_id?: string | null
          image_url?: string | null
          languages?: string | null
          name?: string | null
          payload?: Json | null
          sizes?: string | null
          skills?: string | null
          species_traits?: string | null
          type?: string | null
          updated_at?: string | null
          user_id: string
        }
        Update: {
          adulthood_lifespan?: string | null
          ancestry_traits?: string | null
          ave_hgt_cm?: number | null
          ave_wgt_kg?: number | null
          characteristics?: string | null
          created_at?: string | null
          description?: string | null
          flaws?: string | null
          id?: string
          image_id?: string | null
          image_url?: string | null
          languages?: string | null
          name?: string | null
          payload?: Json | null
          sizes?: string | null
          skills?: string | null
          species_traits?: string | null
          type?: string | null
          updated_at?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_species_image_id_fkey"
            columns: ["image_id"]
            isOneToOne: false
            referencedRelation: "realms_images"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_species_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "user_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      user_techniques: {
        Row: {
          action_type: string | null
          created_at: string | null
          damage: Json
          description: string | null
          duration_type: string | null
          duration_value: number | null
          id: string
          image_id: string | null
          image_url: string | null
          name: string | null
          payload: Json | null
          range_steps: number | null
          updated_at: string | null
          user_id: string
        }
        Insert: {
          action_type?: string | null
          created_at?: string | null
          damage?: Json
          description?: string | null
          duration_type?: string | null
          duration_value?: number | null
          id: string
          image_id?: string | null
          image_url?: string | null
          name?: string | null
          payload?: Json | null
          range_steps?: number | null
          updated_at?: string | null
          user_id: string
        }
        Update: {
          action_type?: string | null
          created_at?: string | null
          damage?: Json
          description?: string | null
          duration_type?: string | null
          duration_value?: number | null
          id?: string
          image_id?: string | null
          image_url?: string | null
          name?: string | null
          payload?: Json | null
          range_steps?: number | null
          updated_at?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_techniques_image_id_fkey"
            columns: ["image_id"]
            isOneToOne: false
            referencedRelation: "realms_images"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_techniques_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "user_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      usernames: {
        Row: {
          user_id: string
          username: string
        }
        Insert: {
          user_id: string
          username: string
        }
        Update: {
          user_id?: string
          username?: string
        }
        Relationships: [
          {
            foreignKeyName: "usernames_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "user_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      vtt_actions: {
        Row: {
          created_at: string
          from_x: number | null
          from_y: number | null
          id: string
          message: string | null
          scene_id: string
          status: string
          to_x: number
          to_y: number
          token_id: string | null
          type: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          from_x?: number | null
          from_y?: number | null
          id: string
          message?: string | null
          scene_id: string
          status?: string
          to_x: number
          to_y: number
          token_id?: string | null
          type: string
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          from_x?: number | null
          from_y?: number | null
          id?: string
          message?: string | null
          scene_id?: string
          status?: string
          to_x?: number
          to_y?: number
          token_id?: string | null
          type?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "vtt_actions_scene_id_fkey"
            columns: ["scene_id"]
            isOneToOne: false
            referencedRelation: "vtt_scenes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "vtt_actions_token_id_fkey"
            columns: ["token_id"]
            isOneToOne: false
            referencedRelation: "vtt_tokens"
            referencedColumns: ["id"]
          },
        ]
      }
      vtt_scenes: {
        Row: {
          campaign_id: string
          created_at: string
          encounter_id: string | null
          fog: Json
          grid: Json
          id: string
          is_active: boolean
          map: Json | null
          name: string
          settings: Json
          updated_at: string
        }
        Insert: {
          campaign_id: string
          created_at?: string
          encounter_id?: string | null
          fog?: Json
          grid?: Json
          id: string
          is_active?: boolean
          map?: Json | null
          name?: string
          settings?: Json
          updated_at?: string
        }
        Update: {
          campaign_id?: string
          created_at?: string
          encounter_id?: string | null
          fog?: Json
          grid?: Json
          id?: string
          is_active?: boolean
          map?: Json | null
          name?: string
          settings?: Json
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "vtt_scenes_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "campaigns"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "vtt_scenes_encounter_id_fkey"
            columns: ["encounter_id"]
            isOneToOne: false
            referencedRelation: "encounters"
            referencedColumns: ["id"]
          },
        ]
      }
      vtt_tokens: {
        Row: {
          color: string
          combatant_id: string | null
          combatant_type: string
          created_at: string
          id: string
          image_url: string | null
          label: string
          locked: boolean
          metadata: Json
          name: string
          scene_id: string
          size: number
          source_id: string | null
          source_type: string | null
          source_user_id: string | null
          updated_at: string
          visible: boolean
          x: number
          y: number
        }
        Insert: {
          color?: string
          combatant_id?: string | null
          combatant_type?: string
          created_at?: string
          id: string
          image_url?: string | null
          label?: string
          locked?: boolean
          metadata?: Json
          name: string
          scene_id: string
          size?: number
          source_id?: string | null
          source_type?: string | null
          source_user_id?: string | null
          updated_at?: string
          visible?: boolean
          x?: number
          y?: number
        }
        Update: {
          color?: string
          combatant_id?: string | null
          combatant_type?: string
          created_at?: string
          id?: string
          image_url?: string | null
          label?: string
          locked?: boolean
          metadata?: Json
          name?: string
          scene_id?: string
          size?: number
          source_id?: string | null
          source_type?: string | null
          source_user_id?: string | null
          updated_at?: string
          visible?: boolean
          x?: number
          y?: number
        }
        Relationships: [
          {
            foreignKeyName: "vtt_tokens_scene_id_fkey"
            columns: ["scene_id"]
            isOneToOne: false
            referencedRelation: "vtt_scenes"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      _official_power_rebuilt_mechanic_part_names: {
        Args: {
          p_action_type: string
          p_area_type: string
          p_damage: Json
          p_duration_type: string
          p_is_reaction: boolean
          p_payload_duration: Json
          p_range_steps: number
        }
        Returns: string[]
      }
      map_feat_tag_phase1: { Args: { raw: string }; Returns: string }
      map_feat_tag_phase2: { Args: { raw: string }; Returns: string }
      map_feat_tag_phase3: { Args: { raw: string }; Returns: string }
      normalize_feat_tags: { Args: { tag_string: string }; Returns: string }
      replace_archetype_levels: {
        Args: { p_archetype_id: string; p_levels: Json }
        Returns: number
      }
    }
    Enums: {
      realms_image_category:
        | "species"
        | "creature"
        | "weapon"
        | "armor"
        | "shield"
        | "equipment"
        | "power"
        | "technique"
      UserRole: "new_player" | "playtester" | "developer" | "admin"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      realms_image_category: [
        "species",
        "creature",
        "weapon",
        "armor",
        "shield",
        "equipment",
        "power",
        "technique",
      ],
      UserRole: ["new_player", "playtester", "developer", "admin"],
    },
  },
} as const
